version: '3.8'

services:
  macromaps-backend:
    build: .
    container_name: macromaps-backend
    ports:
      - "5000:5000"
    environment:
      # API Keys (set these in your .env file or environment)
      - APIFY_API_TOKEN=${APIFY_API_TOKEN:-your-apify-token-here}
      - SUPABASE_URL=${SUPABASE_URL:-your-supabase-url-here}
      - SUPABASE_KEY=${SUPABASE_KEY:-your-supabase-key-here}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      
      # Flask Configuration
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      
      # Gunicorn Configuration
      - WEB_CONCURRENCY=4
      - PORT=5000
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 