[project]
name = "macromaps-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-cors>=6.0.0",
    "flask>=3.1.1",
    "requests>=2.32.3",
    "apify-client>=1.10.0",
]
